apiVersion: v1
kind: Service
metadata:
  name: myclusteripservice
  namespace: test
  labels:
    tier: frontend
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 80
  selector:
    tier: frontend
