apiVersion: v1
kind: Service
metadata:
  name: mynodeportservice
  namespace: test
  labels:
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 31000
  selector:
    tier: frontend
