apiVersion: v1
kind: Pod
metadata:
  name: nginxpodsec
  labels:
    tier: frontend
spec:
  containers:
  - name: nginxcontainer
    image: nginx
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            key: username
            name: sec1
    envFrom:
      - secretRef:
          name: secyaml
