- 
  name: 'Play 1'
  hosts: server1
  tasks:
    - name: 'task 1'
      command: touch /tmp/a.txt
    - name: 'task 2'
      command: touch /tmp/b.txt

- 
  name: 'Play 2'
  hosts: appserver
  tasks:
   - name: 'task1 of play2'
     command: touch /tmp/c.txt
