- 
  name: 'apt service user'
  hosts: server1
  become: true
  become_user: root
  tasks:
    - name: 'apt install'
      apt:
        name: htop
        state: present
        update_cache: yes

    - name: 'service'
      service:
        name: docker
        state: started
        enabled: yes

    - name: 'create user'
      user:
        name: testuser
        password: "testpass"
        state: absent
        remove: yes
